name: Update readme and contributors
on:
    push:
        branches:
            - 'master'

jobs:
    generate-readme:
      name: Generate README.md
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Setup python3
          uses: actions/setup-python@v1
          with:
            python-version: '3.x'
            architecture: 'x64'
        - name: Display Python version
          run: python -c "import sys; print(sys.version)"
        - name: Update README
          run: |
            python3 --version
            bash generate_readme.sh
            cat README.md
